#!/bin/bash
#
#
#   .d8888b.                d8b 888            888                    888  .d88888b.  888b    888 
#  d88P  Y88b               Y8P 888            888                    888 d88P" "Y88b 8888b   888 
#  Y88b.                        888            888                    888 888     888 88888b  888 
#   "Y888b.   888  888  888 888 888888 .d8888b 88888b.   .d88b.   .d88888 888     888 888Y88b 888 
#      "Y88b. 888  888  888 888 888   d88P"    888 "88b d8P  Y8b d88" 888 888     888 888 Y88b888 
#        "888 888  888  888 888 888   888      888  888 88888888 888  888 888     888 888  Y88888 
#  Y88b  d88P Y88b 888 d88P 888 Y88b. Y88b.    888  888 Y8b.     Y88b 888 Y88b. .d88P 888   Y8888 
#   "Y8888P"   "Y8888888P"  888  "Y888 "Y8888P 888  888  "Y8888   "Y88888  "Y88888P"  888    Y888 
#                                                                                                
#  
#                                8888888b.  888888b.  Y88b   d88P 
#                                888   Y88b 888  "88b  Y88b d88P  
#                                888    888 888  .88P   Y88o88P   
#                                888   d88P 8888888K.    Y888P    
#                                8888888P"  888  "Y88b   d888b    
#                                888        888    888  d88888b   
#                                888        888   d88P d88P Y88b  
#                                888        8888888P" d88P   Y88b 
#										switchedonpbx.org
# mondo - 07/05/2011
#
# SwitchedONPBX-1.0
# Author: Federico Pereira <info@opentecnologic.com>
# Author: Ramon Lozano <ramon@solidpc.net>
# Copyright 2011 Federico Pereira (LordBaseX)
# This script is licensed under GNU GPL version 2.0

#deletes mondo from /etc/sop/sop-addons
mkdir -p /etc/sop/
if [ -f /etc/sop/sop-addons ]; then
        sed -i "/mondo/d" /etc/sop/sop-addons
fi

cd /usr/src
PACKAGES="rsync usbmount lshw bzip2 dosfstools syslinux gawk parted mtools buffer wodim genisoimage"
aptitude -y install ${PACKAGES}

arch=`uname -m`
	case $arch in
		i686)
			wget http://mondorescue.muskokamug.org/debian/6.0/afio_2.5-1_i386.deb
			wget http://mondorescue.muskokamug.org/debian/6.0/mindi-busybox_1.18.3-2_i386.deb
			wget http://mondorescue.muskokamug.org/debian/6.0/mindi_2.0.7.7-1_i386.deb
			wget http://mondorescue.muskokamug.org/debian/6.0/mondo_2.2.9.6-1_i386.deb
			dpkg -i afio_2.5-1_i386.deb
			dpkg -i mindi-busybox_1.18.3-2_i386.deb
			dpkg -i mindi_2.0.7.7-1_i386.deb
			dpkg -i mondo_2.2.9.6-1_i386.deb
		;;
		x86_64)
			wget http://mondorescue.muskokamug.org/debian/6.0/afio_2.5-1_amd64.deb
			wget http://mondorescue.muskokamug.org/debian/6.0/mindi-busybox_1.18.3-2_amd64.deb
			wget http://mondorescue.muskokamug.org/debian/6.0/mindi_2.0.7.7-1_amd64.deb
			wget http://mondorescue.muskokamug.org/debian/6.0/mondo_2.2.9.6-1_amd64.deb
			dpkg -i afio_2.5-1_amd64.deb
			dpkg -i mindi-busybox_1.18.3-2_amd64.deb
			dpkg -i mindi_2.0.7.7-1_amd64.deb
			dpkg -i mondo_2.2.9.6-1_amd64.deb
		;;
		*)
			echo "Unsupported architecture, sorry."
		;;
	esac
ln /usr/bin/wodim /usr/bin/cdrecord
ln /usr/bin/genisoimage  /usr/bin/mkisofs

#see if me have a USB stick in there. . . 
lshw -class disk -short
#if not using HA . . .
mkdir -p /state 

#echo "Please wait while we make an image . . . ."
#echo ' type /usr/sbin/mondoarchive  -OVi -9 -d /state  -s 4800m -p "`hostname`_`date +%Y%m%d:%H%M`"  Later to '

#echo "You now have a timestamped self booting iso image in /state, it will restore your system to NOW, without asking any questions"

#adds mondo to/etc/sop/sop-addons
echo "mondo" >> /etc/sop/sop-addons

exit 0





