#!/bin/bash
#
#
#   .d8888b.                d8b 888            888                    888  .d88888b.  888b    888 
#  d88P  Y88b               Y8P 888            888                    888 d88P" "Y88b 8888b   888 
#  Y88b.                        888            888                    888 888     888 88888b  888 
#   "Y888b.   888  888  888 888 888888 .d8888b 88888b.   .d88b.   .d88888 888     888 888Y88b 888 
#      "Y88b. 888  888  888 888 888   d88P"    888 "88b d8P  Y8b d88" 888 888     888 888 Y88b888 
#        "888 888  888  888 888 888   888      888  888 88888888 888  888 888     888 888  Y88888 
#  Y88b  d88P Y88b 888 d88P 888 Y88b. Y88b.    888  888 Y8b.     Y88b 888 Y88b. .d88P 888   Y8888 
#   "Y8888P"   "Y8888888P"  888  "Y888 "Y8888P 888  888  "Y8888   "Y88888  "Y88888P"  888    Y888 
#                                                                                                
#  
#                                8888888b.  888888b.  Y88b   d88P 
#                                888   Y88b 888  "88b  Y88b d88P  
#                                888    888 888  .88P   Y88o88P   
#                                888   d88P 8888888K.    Y888P    
#                                8888888P"  888  "Y88b   d888b    
#                                888        888    888  d88888b   
#                                888        888   d88P d88P Y88b  
#                                888        8888888P" d88P   Y88b 
#										switchedonpbx.org
# rkhunter - 12/05/2011
#
# switched on pbx-1.0
# Author: Ramon Lozano <ramon@solidpc.net>
# Author: Federico Pereira <info@opentecnologic.com>
# Copyright 2011 Federico Pereira (LordBaseX)
# This script is licensed under GNU GPL version 2.0
############################### START VARIABLES #######################################

# Install RKHUNTER
HELPINGWORDS="";

PKGNAME=rkhunter

if [ -f /usr/local/sbin/rkhunter ]; then
        rm -rf /usr/local/sbin/rkhunter
fi

#deletes ${PKGNAME} from /etc/sop/sop-addons
mkdir -p /etc/sop/
if [ -f /etc/sop/sop-addons ]; then
        sed -i "/${PKGNAME}/d" /etc/sop/sop-addons
fi


PKGNAME=rkhunter-138
#deletes ${PKGNAME} from /etc/sop/sop-addons
mkdir -p /etc/sop/
if [ -f /etc/sop/sop-addons ]; then
        sed -i '/${PKGNAME}/d' /etc/sop/sop-addons
fi
#TAG:RKHUNTER GET SOURCE IF NECESSARY
cd /usr/src/

if [ ! -f rkhunter-1.3.8.tar.gz ]; then
	wget http://downloads.sourceforge.net/project/rkhunter/rkhunter/1.3.8/rkhunter-1.3.8.tar.gz
	tar xfvz rkhunter-1.3.8.tar.gz  1>/dev/null
fi

#TAG:RKHUNTER INSTALL

cp programs/rkhunter.conf /etc
cd rkhunter-1.3.8/

./installer.sh --layout default --install 1>/dev/null

#TAG:RKHUNTER EXAMINE SYSTEM

echo "Will now examine your system, please hold . . . "
/usr/local/bin/rkhunter --propupd

#TAG:RKHUNTER AUDIT SYSTEM
echo "If you want to audit your system, run /usr/local/bin/rkhunter -sk -c"

#TAG:RKHUNTER ADD TO MODULES

#adds ${PKGNAME} to /etc/sop/sop-addons
echo "${PKGNAME}" >> /etc/sop/sop-addons
exit 0
