#!/bin/bash
#
#
#   .d8888b.                d8b 888            888                    888  .d88888b.  888b    888 
#  d88P  Y88b               Y8P 888            888                    888 d88P" "Y88b 8888b   888 
#  Y88b.                        888            888                    888 888     888 88888b  888 
#   "Y888b.   888  888  888 888 888888 .d8888b 88888b.   .d88b.   .d88888 888     888 888Y88b 888 
#      "Y88b. 888  888  888 888 888   d88P"    888 "88b d8P  Y8b d88" 888 888     888 888 Y88b888 
#        "888 888  888  888 888 888   888      888  888 88888888 888  888 888     888 888  Y88888 
#  Y88b  d88P Y88b 888 d88P 888 Y88b. Y88b.    888  888 Y8b.     Y88b 888 Y88b. .d88P 888   Y8888 
#   "Y8888P"   "Y8888888P"  888  "Y888 "Y8888P 888  888  "Y8888   "Y88888  "Y88888P"  888    Y888 
#                                                                                                
#  
#                                8888888b.  888888b.  Y88b   d88P 
#                                888   Y88b 888  "88b  Y88b d88P  
#                                888    888 888  .88P   Y88o88P   
#                                888   d88P 8888888K.    Y888P    
#                                8888888P"  888  "Y88b   d888b    
#                                888        888    888  d88888b   
#                                888        888   d88P d88P Y88b  
#                                888        8888888P" d88P   Y88b 
#										switchedonpbx.org
# unattended-install - 07/05/2011
#
# SwitchedONPBX-1.0
# Author: Federico Pereira <info@opentecnologic.com>
# Author: Ramon Lozano <ramon@solidpc.net>
# Copyright 2011 Federico Pereira (LordBaseX)  
# This script is licensed under GNU GPL version 2.0

export DEBIAN_FRONTEND="noninteractive";

#TAG:DOWNLOAD FROM SVN
cd /usr/src
svn co https://switchedonpbx.svn.sourceforge.net/svnroot/switchedonpbx/iso/scripts https://switchedonpbx.svn.sourceforge.net/svnroot/switchedonpbx/iso/apt-key https://switchedonpbx.svn.sourceforge.net/svnroot/switchedonpbx/iso/programs https://switchedonpbx.svn.sourceforge.net/svnroot/switchedonpbx/iso/tools

#TAG:COPY AND CHANGE PERMISSIONS
chmod +x /usr/src/tools/*
cp /usr/src/tools/* /usr/local/sbin/
ln -s /usr/src/scripts/* /usr/local/sbin/


#TAG:CHANGE PERMISSIONS
chmod +x /usr/src/scripts/*

#TAG:CHANGE PERMISSIONS
chmod +x /usr/src/scripts/*
#dos2unix /usr/src/scripts/*

#TAG:COMMON INSTALL
/usr/src/scripts/common-install

#TAG:ASTERISK INSTALATION
/usr/src/scripts/asterisk-18-debs

#TAG:FREEPBX INSTALATION
/usr/src/scripts/freepbx

#TAG:DESELAXTISADOS INSTALATION
/usr/src/scripts/deselastixados

#TAG:WEBMIN INSTALATION
/usr/src/scripts/Webmin

#TAG:RKHUNTER INSTALATION
/usr/src/scripts/RKHunter

#TAG:MONDO INSTALATION
/usr/src/scripts/Mondoarchive

#TAG:AvantFAX INSTALATION
/usr/src/scripts/AvantFAX-333

echo "These are the most relevant passwords for you system:"
cat /etc/sop/passwords

exit 0
